In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
# 返回 dict

def rate_for_report(words,code,date,accr3,accr5,accr3_label,accr5_label,positive,negative):
    
    positive_num = 0
    negative_num = 0
    
    for word in words:
        
        if(word in positive):
            positive_num = positive_num+1
            
        if(word in negative):
            negative_num = negative_num+1
    
    one_dict = {}
    one_dict['code'] = code
    one_dict['date'] = date
    one_dict['accr3'] = accr3
    one_dict['accr3_label'] = accr3_label
    one_dict['accr5'] = accr5
    one_dict['accr5_label'] = accr5_label
    one_dict['positive'] = positive_num
    one_dict['negative'] = negative_num
    one_dict['length'] = len(words)
    
    return one_dict

In [3]:
def rate_dateframe(df,stock_code,positive,negative):
    
    df = df.dropna()
    df = df.reset_index(drop=True)
    
    data_list = []
    
    for i in range(len(df)):
        
        words = list(df.words[i].split("/"))
        code = stock_code
        date = df.ann_date[i]
        accr3 = df.accr3[i]
        accr3_label = df.accr3_label[i]
        accr5 = df.accr5[i]
        accr5_label = df.accr5_label[i]
        
        one_dict = rate_for_report(words,code,date,accr3,accr5,accr3_label,accr5_label,positive,negative)
        
        data_list.append(one_dict)
    
    return data_list

In [5]:
def sentiment_dict_rate(filename,t1,t2):
    
    positive = pd.read_csv("../已有情感词典/positive_combine.csv")
    positive = list(positive['word'])

    negative = pd.read_csv("../已有情感词典/negative_combine.csv")
    negative = list(negative['word'])
    
    df_hs300 = pd.read_csv('data/HS300/' + filename + '.csv')
    stock_code = list(df_hs300['成份代码'])
    foldername = t1+'-'+t2
    
    result = []

    for i in range(len(stock_code)):
        
        one_stock_code = stock_code[i]
        savefilepath = 'data/HS300/' + foldername + '/'+ one_stock_code+'.csv'
        df_report = pd.read_csv(savefilepath)
        
        result0 = rate_dateframe(df_report,one_stock_code,positive,negative)
        result.extend(result0)
        
        if(i%15==0):
            print(i)
    
    result = pd.DataFrame(result)
    
    return result
#     result.to_csv('data/HS300/' + foldername + '/'+ foldername +'_dict_rate.csv')

In [21]:
# 2016 1

sentiment_dict_rate('2015-12-30','20151230','20160613')

0
15
30
45
60
75
90
105
120
135
150
165
180
195
210
225
240
255
270
285

In [6]:
# 2017 1

result = sentiment_dict_rate('2016-12-12','20161212','20170612')

0
15
30
45
60
75
90
105
120
135
150
165
180
195
210
225
240
255
270
285

In [7]:
result.to_csv('data/sentiment_dictionary_result/2017_1.csv',index=False)

In [12]:
df = pd.read_csv("data/HS300/20151230-20160613/000001.SZ.csv")
stock_code = "000001.SZ"

In [13]:
result = rate_dateframe(df,stock_code,positive,negative)
result = pd.DataFrame(result)
result

,code,date,accr3,accr3_label,accr5,accr5_label,positive,negative,length
0,000001.SZ,20160608,0.7966,1,0.0783,1,33,14,437
1,000001.SZ,20160520,0.2525,1,-0.5925,0,54,32,718
2,000001.SZ,20160520,0.2525,1,-0.5925,0,81,17,906
3,000001.SZ,20160520,0.2525,1,-0.5925,0,86,15,930
4,000001.SZ,20160520,0.2525,1,-0.5925,0,27,10,438
5,000001.SZ,20160513,0.4910,1,0.1528,1,62,35,1030
6,000001.SZ,20160421,0.0625,1,0.4996,1,311,151,3361
7,000001.SZ,20160421,0.0625,1,0.4996,1,14,3,153
8,000001.SZ,20160421,0.0625,1,0.4996,1,33,8,493
9,000001.SZ,20160421,0.0625,1,0.4996,1,12,4,73
10,000001.SZ,20160421,0.0625,1,0.4996,1,295,128,2990
11,000001.SZ,20160421,0.0625,1,0.4996,1,1293,214,8594
12,000001.SZ,20160421,0.0625,1,0.4996,1,62,35,1016
13,000001.SZ,20160412,0.4649,1,1.1332,1,7,2,78
14,000001.SZ,20160324,-0.5247,0,-0.8784,0,80,12,604
15,000001.SZ,20160324,-0.5247,0,-0.8784,0,340,42,1938
16,000001.SZ,20160324,-0.5247,0,-0.8784,0,101,33,687
17,000001.SZ,20160324,-0.5247,0,-0.8784,0,200,70,2298
18,000001.SZ,20160324,-0.5247,0,-0.8784,0,170,22,1005
19,000001.SZ,20160315,-0.3703,0,1.4266,1,493,120,4216
20,000001.SZ,20160315,-0.3703,0,1.4266,1,557,175,5274
21,000001.SZ,20160315,-0.3703,0,1.4266,1,101,12,432
22,000001.SZ,20160315,-0.3703,0,1.4266,1,3492,1628,32945
23,000001.SZ,20160315,-0.3703,0,1.4266,1,186,21,1420
24,000001.SZ,20160315,-0.3703,0,1.4266,1,185,16,1963
25,000001.SZ,20160315,-0.3703,0,1.4266,1,1120,473,10597
26,000001.SZ,20160310,1.1254,1,1.9031,1,70,14,857
27,000001.SZ,20160310,1.1254,1,1.9031,1,44,19,294
28,000001.SZ,20160310,1.1254,1,1.9031,1,17,2,174
29,000001.SZ,20160310,1.1254,1,1.9031,1,3310,1586,34250
30,000001.SZ,20160310,1.1254,1,1.9031,1,17,5,109
31,000001.SZ,20160310,1.1254,1,1.9031,1,79,24,657
32,000001.SZ,20160310,1.1254,1,1.9031,1,2645,404,14931
33,000001.SZ,20160310,1.1254,1,1.9031,1,71,13,760
34,000001.SZ,20160310,1.1254,1,1.9031,1,42,10,666
35,000001.SZ,20160310,1.1254,1,1.9031,1,66,12,798
36,000001.SZ,20160310,1.1254,1,1.9031,1,12,7,113
37,000001.SZ,20160310,1.1254,1,1.9031,1,865,350,4851
38,000001.SZ,20160310,1.1254,1,1.9031,1,957,841,14699
39,000001.SZ,20160310,1.1254,1,1.9031,1,811,97,4994
40,000001.SZ,20160310,1.1254,1,1.9031,1,15,10,474
41,000001.SZ,20160310,1.1254,1,1.9031,1,92,23,651
42,000001.SZ,20160310,1.1254,1,1.9031,1,124,30,796
43,000001.SZ,20160310,1.1254,1,1.9031,1,127,38,823
44,000001.SZ,20160308,0.1062,1,-0.0201,0,15,3,106
45,000001.SZ,20160227,1.6890,1,0.6257,1,14,3,108
46,000001.SZ,20160226,1.2870,1,0.8665,1,84,8,546
47,000001.SZ,20160121,0.6984,1,0.1497,1,22,5,138
48,000001.SZ,20160119,-0.6182,0,-1.2037,0,9,2,115
49,000001.SZ,20160109,3.2160,1,2.9391,1,10,2,63
50,000001.SZ,20160106,1.2392,1,1.2330,1,6,2,63
51,000001.SZ,20160105,1.8516,1,1.8462,1,9,2,100